spring:
  data:
    mongodb:
      username: root
      password: root
      database: db
      host: localhost
      port: 27017
      authentication-database: admin

javers:
  mongodb:
    username: root
    password: root
    database: db
    host: localhost
    port: 27017
    authentication-database: admin