spring:
  data:
    mongodb:
      username: root
      password: root
      database: proposals
      host: localhost
      port: 27017
      authentication-database: admin

javers:
  mongodb:
    username: root
    password: root
    database: proposalschangelog
    host: localhost
    port: 27017
    authentication-database: admin